### ISSUE TITLE
Support pseudos that target other rules

### ISSUE THREAD

**Issue by nevir** [convoyinc/dapper#17]
Frequently when authoring components, you want to be able to react to pseudos like `:hover` when they target the _component_, not the element you're styling.  It would be nice if we could target other elements when scoping to a pseudo selector.

Some options to consider:

```ts
button: {
  '{root}:hover': {
    backgroundColor: 'mauve',
  },
}
```

```ts
button: {
  ':hover(root)': {
    backgroundColor: 'mauve',
  },
}
```

```ts
root: {
  ':hover': {
    '&button': {
      backgroundColor: 'mauve',
    },
  },
}
```

**Comment by RylanH** [comment]
& is already saved for parent reference so the third option doesn't make sense. The second one seems like it could conflict with a future version of CSS and hard to distinguish a pseudo class or element we should just not touch and something we need to rewrite. The first option seems about right, but given the nesting rules would result in 
```
button .root-class-name:hover {
  background-color: mauve;
}
```

I think the options should be:

```
root: {
  ':hover': {
    '{button}': {
      padding: 5,
    },
  },
},
button: {
  padding: 10,
},
```
and
```
root: {
    color: 'red',
  },
  button: {
    '{root}:hover &': {
      padding: 10,
    },
  },
```
Which is really the same thing replacing curly brace placeholders. The benefit of the second is that you are specifying the button style under button instead of under root. The second one does a replacement of the & with the parent selector, which can actually get a bit strange.

**Comment by RylanH** [comment]
Or maybe in css variables style: 
```
root: {
  color: 'red',
  ':hover': {
    'style(button)': {
      padding: 5,
    }
  }
},
```

**Comment by nevir** [comment]
So far I'm a fan of `{ruleName}` - it is simple & flexible (just string replacement).  And we should avoid valid CSS syntax where possible, to avoid ambiguity of whether it's Dapper or the browser parsing the rule

**Comment by RylanH** [comment]
Okay, then I think the best solution is 
```
root: {
  color: 'red',
},
button: {
  '{root}:hover &': {
    padding: 10,
  },
},
```

**Comment by RylanH** [comment]
Fixed in https://github.com/convoyinc/dapper/pull/31
